package com.bounce.formapp.util

const val BASE_URL = "http://192.168.0.101:3000"
const val IS_DEBUG_ON = true // TODO: false on live

const val INTENT_EXTRA_OPEN_AS_EDIT_FORM = "INTENT_EXTRA_OPEN_AS_EDIT_FORM"
const val INTENT_EXTRA_SELECTED_ROW: String = "INTENT_EXTRA_SELECTED_ROW"

const val REQUEST_CODE_PICK_IMAGE_PERMISSION = 10001
const val REQUEST_CODE_CAPTURE_IMAGE_PERMISSION = 10002

const val REQUEST_CODE_PICK_IMAGE = 10011
const val REQUEST_CODE_CAPTURE_IMAGE = 10012
